-- ...existing code...
CREATE TABLE person (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rut VARCHAR(50),
  nombre VARCHAR(100),
  apellido VARCHAR(100),
  fecha_nacimiento DATE,
  direccion VARCHAR(255),
  calle VARCHAR(100),
  comuna VARCHAR(100),
  region VARCHAR(100)
);
-- ...existing code...